FROM oven/bun:1.3.3-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

COPY server ./server
COPY src ./src
COPY tsconfig.json ./

ENV NODE_ENV=production
ENV PORT=8787
EXPOSE 8787

CMD ["bun", "run", "api"]
